### ISSUE TITLE
Archers have got all the same skin and clothing after 1

### ISSUE THREAD

**Issue by RapleAQN** [RapleAQN/RealmEye-originally-by-BlackRayquaza-#2]
Mistake I am too lazy to fix because if I do, archers appear everywhere. Meh. (。ヘ°) (。ヘ°) (。ヘ°) (。ヘ°) ヽ(。_°)ノ ヽ(。_°)ノ ヽ(。_°)ノ ヽ(。_°)ノ

**Comment by BlackRayquaza** [comment]
Im releasing an updated version soon. I have screenshots in one of my mpgh threads.

**Comment by RapleAQN** [comment]
Seems good, I was waiting for you to release yours haha
